Configuratron:
  use_only:
    - mmidb
  preload: True
  sfreq: 256
  deep1010:
    return_mask: False

encoder_weights: data/checkpoints/encoder.pt
context_weights: data/checkpoints/contextualizer.pt

datasets: !include configs/downstream_datasets.yml

